exclude: ^.*\/(aob_py3|appserver)\/.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-json
        types: [text] # the json type is too restrictive
        files: \.(json|samples)$
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.*cim.rst$
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/myint/rstcheck
    rev: v6.0.0rc3
    hooks:
      - id: rstcheck
        args: ["--config", ".rstcheck.cfg"]
        additional_dependencies: ["rstcheck[sphinx]"]
        exclude: \.*cim.rst$
