version: '3.8'

services:
  censys_splunk:
    image: splunk/splunk
    container_name: censys_splunk
    ports:
      - 8000:8000
    restart: "no"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HOME=/opt/splunk
      - SPLUNK_PASSWORD=I<3bigDATA
    volumes:
      - ./packages/Splunk_TA_censys/stage:/opt/splunk/etc/apps/Splunk_TA_censys
      - ./packages/censys/stage:/opt/splunk/etc/apps/censys
